# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: vm-power
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge